defaults:
 # base trident datamodule configuration
 - trident

dataset_cfg:
  # - Notes:
  #   - dataset_cfg inherits 
  #       >> _target_: datasets.load.load_dataset
  #     from `trident` defaults
  # --- dataset_cfg-level namespace ---
  _method_: # get methods of _target_ object
    # _method_ is trident syntax to call methods onto objects instantiated by _target_
    # IMPORTANT: the function **has to** return the dataset (no in-place mutation!)
    # Notes:
    # - _method_ is most relevant for Huggingface datasts
    #   (i.e. `_target_: datasets.load.load_dataset`)
    #   but any fn yielding a class with "preprocessing" methods works (e.g. pd.DataFrame)
    map: # dataset.map -> tokenization
      # kwargs for dataset.map
      function:
        _target_: src.tasks.text_classification.processor.preprocess_fn
        _partial_: true
        column_names:
          text: premise
          text_pair: hypothesis
    # unify output format of MNLI and XNLI
    set_format:
      columns:
        - "input_ids"
        - "attention_mask"
        - "label"
  # -----------------------------------

  train:
    # inherits  dataset_cfg-level namespace
    path: glue  # `datasets.load.load_dataset` variables
    name: mnli  # `datasets.load.load_dataset` variables
    split: train  # split-specific `datasets.load.load_dataset` variable

  # comment out datasets you don't want to evaluate on
  val:
    # Huggingface datasets syntax to concatenate these splits
    _datasets_:
      validation_xnli_en:
        path: xnli
        name: en
        split: validation
      validation_xnli_es:
        path: xnli
        name: es
        split: validation
      validation_xnli_de:
        path: xnli
        name: de
        split: validation
      validation_xnli_fr:
        path: xnli
        name: fr
        split: validation
      validation_xnli_el:
        path: xnli
        name: el
        split: validation
      validation_xnli_bg:
        path: xnli
        name: bg
        split: validation
      validation_xnli_ru:
        path: xnli
        name: ru
        split: validation
      validation_xnli_tr:
        path: xnli
        name: tr
        split: validation
      validation_xnli_ar:
        path: xnli
        name: ar
        split: validation
      validation_xnli_vi:
        path: xnli
        name: vi
        split: validation
      validation_xnli_th:
        path: xnli
        name: th
        split: validation
      validation_xnli_zh:
        path: xnli
        name: zh
        split: validation
      validation_xnli_hi:
        path: xnli
        name: hi
        split: validation
      validation_xnli_sw:
        path: xnli
        name: sw
        split: validation
      validation_xnli_ur:
        path: xnli
        name: ur
        split: validation
      validation_anli_aym:
        path: americas_nli
        name: aym
        split: validation
      validation_anli_bzd:
        path: americas_nli
        name: bzd
        split: validation
      validation_anli_cni:
        path: americas_nli
        name: cni
        split: validation
      validation_anli_gn:
        path: americas_nli
        name: gn
        split: validation
      validation_anli_hch:
        path: americas_nli
        name: hch
        split: validation
      validation_anli_nah:
        path: americas_nli
        name: nah
        split: validation
      validation_anli_oto:
        path: americas_nli
        name: oto
        split: validation
      validation_anli_quy:
        path: americas_nli
        name: quy
        split: validation
      validation_anli_shp:
        path: americas_nli
        name: shp
        split: validation
      validation_anli_tar:
        path: americas_nli
        name: tar
        split: validation
      test_xnli_en:
        path: xnli
        name: en
        split: test
      test_xnli_es:
        path: xnli
        name: es
        split: test
      test_xnli_de:
        path: xnli
        name: de
        split: test
      test_xnli_fr:
        path: xnli
        name: fr
        split: test
      test_xnli_el:
        path: xnli
        name: el
        split: test
      test_xnli_bg:
        path: xnli
        name: bg
        split: test
      test_xnli_ru:
        path: xnli
        name: ru
        split: test
      test_xnli_tr:
        path: xnli
        name: tr
        split: test
      test_xnli_ar:
        path: xnli
        name: ar
        split: test
      test_xnli_vi:
        path: xnli
        name: vi
        split: test
      test_xnli_th:
        path: xnli
        name: th
        split: test
      test_xnli_zh:
        path: xnli
        name: zh
        split: test
      test_xnli_hi:
        path: xnli
        name: hi
        split: test
      test_xnli_sw:
        path: xnli
        name: sw
        split: test
      test_xnli_ur:
        path: xnli
        name: ur
        split: test
      test_anli_aym:
        path: americas_nli
        name: aym
        split: test
      test_anli_bzd:
        path: americas_nli
        name: bzd
        split: test
      test_anli_cni:
        path: americas_nli
        name: cni
        split: test
      test_anli_gn:
        path: americas_nli
        name: gn
        split: test
      test_anli_hch:
        path: americas_nli
        name: hch
        split: test
      test_anli_nah:
        path: americas_nli
        name: nah
        split: test
      test_anli_oto:
        path: americas_nli
        name: oto
        split: test
      test_anli_quy:
        path: americas_nli
        name: quy
        split: test
      test_anli_shp:
        path: americas_nli
        name: shp
        split: test
      test_anli_tar:
        path: americas_nli
        name: tar
        split: test
      validation_indicxnli_as:
        path: Divyanshu/indicxnli
        name: as
        split: validation
      validation_indicxnli_bn:
        path: Divyanshu/indicxnli
        name: bn
        split: validation
      validation_indicxnli_gu:
        path: Divyanshu/indicxnli
        name: gu
        split: validation
      validation_indicxnli_hi:
        path: Divyanshu/indicxnli
        name: hi
        split: validation
      validation_indicxnli_kn:
        path: Divyanshu/indicxnli
        name: kn
        split: validation
      validation_indicxnli_ml:
        path: Divyanshu/indicxnli
        name: ml
        split: validation
      validation_indicxnli_mr:
        path: Divyanshu/indicxnli
        name: mr
        split: validation
      validation_indicxnli_or:
        path: Divyanshu/indicxnli
        name: or
        split: validation
      validation_indicxnli_pa:
        path: Divyanshu/indicxnli
        name: pa
        split: validation
      validation_indicxnli_ta:
        path: Divyanshu/indicxnli
        name: ta
        split: validation
      validation_indicxnli_te:
        path: Divyanshu/indicxnli
        name: te
        split: validation
      test_indicxnli_as:
        path: Divyanshu/indicxnli
        name: as
        split: test
      test_indicxnli_bn:
        path: Divyanshu/indicxnli
        name: bn
        split: test
      test_indicxnli_gu:
        path: Divyanshu/indicxnli
        name: gu
        split: test
      test_indicxnli_hi:
        path: Divyanshu/indicxnli
        name: hi
        split: test
      test_indicxnli_kn:
        path: Divyanshu/indicxnli
        name: kn
        split: test
      test_indicxnli_ml:
        path: Divyanshu/indicxnli
        name: ml
        split: test
      test_indicxnli_mr:
        path: Divyanshu/indicxnli
        name: mr
        split: test
      test_indicxnli_or:
        path: Divyanshu/indicxnli
        name: or
        split: test
      test_indicxnli_pa:
        path: Divyanshu/indicxnli
        name: pa
        split: test
      test_indicxnli_ta:
        path: Divyanshu/indicxnli
        name: ta
        split: test
      test_indicxnli_te:
        path: Divyanshu/indicxnli
        name: te
        split: test
  test:
    # Huggingface datasets syntax to concatenate these splits
    _datasets_:
      validation_xnli_en:
        path: xnli
        name: en
        split: validation
      validation_xnli_es:
        path: xnli
        name: es
        split: validation
      validation_xnli_de:
        path: xnli
        name: de
        split: validation
      validation_xnli_fr:
        path: xnli
        name: fr
        split: validation
      validation_xnli_el:
        path: xnli
        name: el
        split: validation
      validation_xnli_bg:
        path: xnli
        name: bg
        split: validation
      validation_xnli_ru:
        path: xnli
        name: ru
        split: validation
      validation_xnli_tr:
        path: xnli
        name: tr
        split: validation
      validation_xnli_ar:
        path: xnli
        name: ar
        split: validation
      validation_xnli_vi:
        path: xnli
        name: vi
        split: validation
      validation_xnli_th:
        path: xnli
        name: th
        split: validation
      validation_xnli_zh:
        path: xnli
        name: zh
        split: validation
      validation_xnli_hi:
        path: xnli
        name: hi
        split: validation
      validation_xnli_sw:
        path: xnli
        name: sw
        split: validation
      validation_xnli_ur:
        path: xnli
        name: ur
        split: validation
      validation_anli_aym:
        path: americas_nli
        name: aym
        split: validation
      validation_anli_bzd:
        path: americas_nli
        name: bzd
        split: validation
      validation_anli_cni:
        path: americas_nli
        name: cni
        split: validation
      validation_anli_gn:
        path: americas_nli
        name: gn
        split: validation
      validation_anli_hch:
        path: americas_nli
        name: hch
        split: validation
      validation_anli_nah:
        path: americas_nli
        name: nah
        split: validation
      validation_anli_oto:
        path: americas_nli
        name: oto
        split: validation
      validation_anli_quy:
        path: americas_nli
        name: quy
        split: validation
      validation_anli_shp:
        path: americas_nli
        name: shp
        split: validation
      validation_anli_tar:
        path: americas_nli
        name: tar
        split: validation
      test_xnli_en:
        path: xnli
        name: en
        split: test
      test_xnli_es:
        path: xnli
        name: es
        split: test
      test_xnli_de:
        path: xnli
        name: de
        split: test
      test_xnli_fr:
        path: xnli
        name: fr
        split: test
      test_xnli_el:
        path: xnli
        name: el
        split: test
      test_xnli_bg:
        path: xnli
        name: bg
        split: test
      test_xnli_ru:
        path: xnli
        name: ru
        split: test
      test_xnli_tr:
        path: xnli
        name: tr
        split: test
      test_xnli_ar:
        path: xnli
        name: ar
        split: test
      test_xnli_vi:
        path: xnli
        name: vi
        split: test
      test_xnli_th:
        path: xnli
        name: th
        split: test
      test_xnli_zh:
        path: xnli
        name: zh
        split: test
      test_xnli_hi:
        path: xnli
        name: hi
        split: test
      test_xnli_sw:
        path: xnli
        name: sw
        split: test
      test_xnli_ur:
        path: xnli
        name: ur
        split: test
      test_anli_aym:
        path: americas_nli
        name: aym
        split: test
      test_anli_bzd:
        path: americas_nli
        name: bzd
        split: test
      test_anli_cni:
        path: americas_nli
        name: cni
        split: test
      test_anli_gn:
        path: americas_nli
        name: gn
        split: test
      test_anli_hch:
        path: americas_nli
        name: hch
        split: test
      test_anli_nah:
        path: americas_nli
        name: nah
        split: test
      test_anli_oto:
        path: americas_nli
        name: oto
        split: test
      test_anli_quy:
        path: americas_nli
        name: quy
        split: test
      test_anli_shp:
        path: americas_nli
        name: shp
        split: test
      test_anli_tar:
        path: americas_nli
        name: tar
        split: test
      test_indicxnli_as:
        path: Divyanshu/indicxnli
        name: as
        split: test
      test_indicxnli_bn:
        path: Divyanshu/indicxnli
        name: bn
        split: test
      test_indicxnli_gu:
        path: Divyanshu/indicxnli
        name: gu
        split: test
      test_indicxnli_hi:
        path: Divyanshu/indicxnli
        name: hi
        split: test
      test_indicxnli_kn:
        path: Divyanshu/indicxnli
        name: kn
        split: test
      test_indicxnli_ml:
        path: Divyanshu/indicxnli
        name: ml
        split: test
      test_indicxnli_mr:
        path: Divyanshu/indicxnli
        name: mr
        split: test
      test_indicxnli_or:
        path: Divyanshu/indicxnli
        name: or
        split: test
      test_indicxnli_pa:
        path: Divyanshu/indicxnli
        name: pa
        split: test
      test_indicxnli_ta:
        path: Divyanshu/indicxnli
        name: ta
        split: test
      test_indicxnli_te:
        path: Divyanshu/indicxnli
        name: te
        split: test
