defaults:
 # base trident datamodule configuration
  - trident

datamodule_cfg:
  remove_unused_columns: true
  keep_raw_dataset: true

dataset_cfg:
  path: ${hydra:runtime.cwd}/tydiqa_goldp_dataset.py
  _method_:
    map:
      batched: true
      function:
        _target_: src.tasks.question_answering.processor.preprocess_fn_val_test
        _partial_: true
        tokenizer:
          # "When splitting up a long document into chunks, how much stride to take between chunks."
          stride: 128
          padding: "max_length"
          max_length: 384
          return_overflowing_tokens: true  # do not change
          return_offsets_mapping: true  # do not change
        column_names:
          context: context
          question: question
          answers: answers
      remove_columns:
        - "id"
        - "context"
        - "question"
        - "answers"

  train:
    _method_:
      map:
        function:
          _target_: src.tasks.question_answering.processor.preprocess_fn_train
    name: en
    split: train

  val:
    # name: ar
    # split: test
    _datasets_:
      test_tydiqa_en:
        name: en
        split: dev
      validation_tydiqa_ar:
        name: ar
        split: train
      validation_tydiqa_bn:
        name: bn
        split: train
      validation_tydiqa_fi:
        name: fi
        split: train
      validation_tydiqa_id:
        name: id
        split: train
      validation_tydiqa_ko:
        name: ko
        split: train
      validation_tydiqa_ru:
        name: ru
        split: train
      validation_tydiqa_sw:
        name: sw
        split: train
      validation_tydiqa_te:
        name: te
        split: train
      test_tydiqa_ar:
        name: ar
        split: dev
      test_tydiqa_bn:
        name: bn
        split: dev
      test_tydiqa_fi:
        name: fi
        split: dev
      test_tydiqa_id:
        name: id
        split: dev
      test_tydiqa_ko:
        name: ko
        split: dev
      test_tydiqa_ru:
        name: ru
        split: dev
      test_tydiqa_sw:
        name: sw
        split: dev
      test_tydiqa_te:
        name: te
        split: dev

  test: 
    _datasets_:
      test_tydiqa_en:
        name: en
        split: dev
      validation_tydiqa_ar:
        name: ar
        split: train
      validation_tydiqa_bn:
        name: bn
        split: train
      validation_tydiqa_fi:
        name: fi
        split: train
      validation_tydiqa_id:
        name: id
        split: train
      validation_tydiqa_ko:
        name: ko
        split: train
      validation_tydiqa_ru:
        name: ru
        split: train
      validation_tydiqa_sw:
        name: sw
        split: train
      validation_tydiqa_te:
        name: te
        split: train
      test_tydiqa_ar:
        name: ar
        split: dev
      test_tydiqa_bn:
        name: bn
        split: dev
      test_tydiqa_fi:
        name: fi
        split: dev
      test_tydiqa_id:
        name: id
        split: dev
      test_tydiqa_ko:
        name: ko
        split: dev
      test_tydiqa_ru:
        name: ru
        split: dev
      test_tydiqa_sw:
        name: sw
        split: dev
      test_tydiqa_te:
        name: te
        split: dev
