wikiann = [
    "wikiann_am",
    "wikiann_ar",
    "wikiann_ay",
    "wikiann_bg",
    "wikiann_de",
    "wikiann_el",
    "wikiann_en",
    "wikiann_es",
    "wikiann_fi",
    "wikiann_fr",
    "wikiann_he",
    "wikiann_hi",
    "wikiann_hu",
    "wikiann_ig",
    "wikiann_ja",
    "wikiann_qu",
    "wikiann_ru",
    "wikiann_rw",
    "wikiann_sw",
    "wikiann_ta",
    "wikiann_te",
    "wikiann_tr",
    "wikiann_ur",
    "wikiann_vi",
    "wikiann_yo",
    "wikiann_zh",
]
wikiann_mult = [
    "wikiann_en",
    "wikiann_ar",
    "wikiann_fi",
    "wikiann_hu",
    "wikiann_sw",
    "wikiann_ta",
    "wikiann_tr",
    "wikiann_ur",
    "wikiann_vi",
    "wikiann_zh",
]

masakhaner = [
    "masakhaner_amh",
    "masakhaner_hau",
    "masakhaner_ibo",
    "masakhaner_kin",
    "masakhaner_lug",
    "masakhaner_luo",
    "masakhaner_pcm",
    "masakhaner_swa",
    "masakhaner_wol",
    "masakhaner_yor",
]

masakhaner2 = [
    "masakhaner2_xho",
    "masakhaner2_ewe",
    "masakhaner2_twi",
    "masakhaner2_sna",
    "masakhaner2_swa",
    "masakhaner2_zul",
    "masakhaner2_ibo",
    "masakhaner2_bam",
    "masakhaner2_bbj",
    "masakhaner2_nya",
    "masakhaner2_lug",
    "masakhaner2_fon",
    "masakhaner2_wol",
    "masakhaner2_pcm",
    "masakhaner2_hau",
    "masakhaner2_kin",
    "masakhaner2_tsn",
    "masakhaner2_yor",
    "masakhaner2_mos",
]

tydiqa = [
    "tydiqa_en",
    "tydiqa_ar",
    "tydiqa_bn",
    "tydiqa_fi",
    "tydiqa_id",
    "tydiqa_ko",
    "tydiqa_ru",
    "tydiqa_sw",
    "tydiqa_te",
]


pawsx = [
    "pawsx_de",
    "pawsx_en",
    "pawsx_es",
    "pawsx_fr",
    "pawsx_ja",
    "pawsx_ko",
    "pawsx_zh",
]

xnli_en = ["xnli_en"]
xnli = [
    "xnli_en",
    "xnli_ar",
    "xnli_bg",
    "xnli_de",
    "xnli_el",
    "xnli_en",
    "xnli_es",
    "xnli_fr",
    "xnli_hi",
    "xnli_ru",
    "xnli_sw",
    "xnli_th",
    "xnli_tr",
    "xnli_ur",
    "xnli_vi",
    "xnli_zh",
]

amnli = [
    "anli_aym",
    "anli_bzd",
    "anli_gn",
    "anli_hch",
    "anli_quy",
    "anli_shp",
    "anli_tar",
    "anli_cni",
    "anli_nah",
    "anli_oto",
]

indicxnli = [
    "indicxnli_as",
    "indicxnli_bn",
    "indicxnli_gu",
    "indicxnli_hi",
    "indicxnli_kn",
    "indicxnli_ml",
    "indicxnli_mr",
    "indicxnli_or",
    "indicxnli_pa",
    "indicxnli_ta",
    "indicxnli_te",
]

amnli_mult = [
    "xnli_en",
    "anli_aym",
    "anli_bzd",
    "anli_gn",
    "anli_hch",
    "anli_quy",
    "anli_shp",
    "anli_tar",
]

jampatois = [
    "jampatois",
]

udpos = [
    "udpos_English",
    "udpos_Afrikaans",
    "udpos_Arabic",
    "udpos_Basque",
    "udpos_Bulgarian",
    "udpos_Chinese",
    "udpos_Dutch",
    "udpos_Estonian",
    "udpos_Finnish",
    "udpos_French",
    "udpos_German",
    "udpos_Greek",
    "udpos_Hebrew",
    "udpos_Hindi",
    "udpos_Hungarian",
    "udpos_Indonesian",
    "udpos_Italian",
    "udpos_Japanese",
    "udpos_Kazakh",
    "udpos_Korean",
    "udpos_Marathi",
    "udpos_Persian",
    "udpos_Portuguese",
    "udpos_Russian",
    "udpos_Spanish",
    "udpos_Tagalog",
    "udpos_Tamil",
    "udpos_Telugu",
    "udpos_Thai",
    "udpos_Turkish",
    "udpos_Urdu",
    "udpos_Vietnamese",
    "udpos_Yoruba",
]

udpos_mult = [
    "udpos_English",
    "udpos_Arabic",
    "udpos_Basque",
    "udpos_Chinese",
    "udpos_Finnish",
    "udpos_German",
    "udpos_Indonesian",
    "udpos_Japanese",
    "udpos_Turkish",
    "udpos_Urdu",
]
